name: Release Build

on:
  workflow_dispatch:
    inputs:
      version_name:
        description: 'Version 0.1.0'
        required: true
        type: string
      release_notes:
        description: 'Release notes'
        required: false
        type: string
        default: 'New release'

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode keystore (if available)
        if: ${{ secrets.KEYSTORE_BASE64 != '' }}
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > release.keystore
        continue-on-error: true

      - name: Build release APK
        run: ./gradlew assembleRelease --stacktrace
        env:
          KEYSTORE_FILE: ../release.keystore
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        continue-on-error: true

      - name: Build release AAB (App Bundle)
        run: ./gradlew bundleRelease --stacktrace
        env:
          KEYSTORE_FILE: ../release.keystore
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        continue-on-error: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ inputs.version_name }}
          name: Release ${{ inputs.version_name }}
          body: ${{ inputs.release_notes }}
          files: |
            app/build/outputs/apk/release/*.apk
            app/build/outputs/bundle/release/*.aab
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk-v${{ inputs.version_name }}
          path: app/build/outputs/apk/release/*.apk
          retention-days: 90

      - name: Upload Release AAB
        uses: actions/upload-artifact@v4
        with:
          name: release-aab-v${{ inputs.version_name }}
          path: app/build/outputs/bundle/release/*.aab
          retention-days: 90
        continue-on-error: true

